### PR TITLE
Proposal: Reorganization of API Definitions to specific files 

### PR DESCRIPTION
**Pull request by alexaverill**
Hey @forceflow1049 
I figured this was going to be easier to discuss with some code rather then opening an issue. 
I started on some updates to split the API definition that currently is living in the Exhibitera_Apps.py file into separate files for each set of routes. 

My thinking here is that reducing the entrypoint file and having the API endpoints in an api/{ROUTE} folder structure makes it easier to navigate the codebase at a glance and will help reduce any chance of merge conflicts as people contribute to the project. 

I started by just moving over the system and definition routes since they were the smallest and easiest to put some tests around. 

My overall thought was to split out the following routes into folders and add tests to cover the changes 
1. api/system_api/
2. api/definitions/
3. api/dmx/
4. api/data/
5. api/ <- this would likely be put into a root folder but also could stay in the exhibitera_apps file as well 
6. api/files/ 

What are your thoughts? 

If we want to move forward I would likely split 3-6 into individual PRs and slowly chip away over the next while

### CODE REVIEW

**Comment by forceflow1049** [comment]
@alexaverill I think this is a GREAT idea...

I've been wanting to split the endpoints using routes for a while; it just keeps getting pushed off behind feature requests. So this would be a huge contribution. I think splitting into many small PRs is a good idea, as trying to move functions to new files while merging in changes from other feature branches sounds like a PITA. As you make PRs, I can merge them into my feature branches (mainly the setup wizard one, which is going to be a giant, sprawling merge to cover all the different apps uniformly, but shouldn't mess with the endpoints at all).

I'd also really appreciate your input on unit testing. Unit tests are obviously really important, but honestly I'm not knowledgeable about how to implement them in an app like this that is so heavy on client-server interactions. But past releases have had a number of regressions that should have been caught prior to release through some basic testing. The surface area of the app is just enormous with so many endpoints that are reliant on a complex app state.

**Comment by alexaverill** [comment]
Cool, I will keep slowly moving forward on splitting them out. This one should be good to go, so I will move onto the DMX endpoints next

In terms of tests I think the easiest way is to slowly add tests as different areas are changed or touched. I have been mainly thinking about it as End to End (E2E) tests to ensure that the changes I make aren't causing regressions. So for those tests I start by writing the test against the existing code, then make my changes. 

 In addition to E2E tests adding in unit tests to cover individual functions would also be good, I can dig around and find some areas to add some unit tests as an example as well.

**Comment by forceflow1049** [comment]
Hi @alexaverill, took a look at this tonight—it's off to a great start! A few comments:

- For uniformity, should we change "system_api" to just "system" so that it matches "definitions"? That way it is the same pattern for accessing all the routes.
- I ran the test suite, but one of the tests failed—`test_definition_api_flow`
- The Exhibitera modules, such as `helper_files`, aren't recognized by my IDE (PyCharm) when importing from within the new routes files. They obviously work at runtime based on how fastAPI utilizes them, but they break basic IDE tooling like function autocomplete. Do we need to make some kind of other change to the overall package to make this work?

I pushed a commit to the PR that removed a bunch of unused imports from the route files, as well as fixing some PEP-8 issues. I also pushed a few commits to the main Dev_5.2 branch that include changes to the endpoints so that they get included in your work.

**Comment by alexaverill** [comment]
Hey @forceflow1049 
For the system naming I had wanted to make sure it was distinct from the default system library, having both import system, and a from api.system import system seems confusing. We could name the folder system and leave the file as system_api, that would have it be from api.system import system_api. 

What error were you getting? 
If it was `E       FileNotFoundError: [Errno 2] No such file or directory: './definitions'` try running pytest in the apps folder and seeing if that passes. 

I haven't really used Pycharm, but I downloaded a trial and it looks like this stackoverflow answer about marking a folder as a source root fixes autocomplete for Pycharm https://stackoverflow.com/a/35553721

And thanks for that cleanup! 

I'll hopefully have some of the DMX split out in a new PR later this weekend.

**Comment by forceflow1049** [comment]
Hi @alexaverill thanks for the comprehensive response. Your fix for PyCharm worked for me, as did running pytest from the apps directory. 

The logic makes sense for the `system_api` routes, but is there actually a default `system` module? if I do `import system` in Python 3.12, I get a `ModuleNotFoundError`. I think that's the last blocker for accepting this PR!

**Comment by alexaverill** [comment]
@forceflow1049 you are right, python uses sys instead of system. My brain was still in C# land where its under sytem. I updated the naming to use system.

**Pull request merged**
